version: "3.9"
services:
  web:
    build: .
    ports:
      - 8000:8000
    entrypoint: /bin/sh
    command: scripts/run.sh
    volumes:
      - ./optimuspy:/optimuspy/optimuspy
      - ./static:/optimuspy/static
      - ./web:/optimuspy/web
